webshop/shop/urls.py
from django.conf.urls import url
#test
from . import views

app_name = "shop"

urlpatterns = [
    url(r'^$', views.index, name='index'),
]


webshop/webshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
]


webshop/shop/models.py
from __future__ import unicode_literals
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    lagersaldo = models.IntegerField()
    description = models.TextField()
    main_image = models.ImageField()


class DetailedProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField()

webshop/shop/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    # return HttpResponse("Hello, world. You're at the shop index.")
    return render(request, "shop/index.html")

webshop/shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'shop:index' %}">Webshop</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

        <!-- Footer -->

</body>
</html>

webshop/shop/templates/shop/index.html
{% extends 'shop/base.html' %}
<!-- {% block albums_active %}active{% endblock %} -->

{% block body %}

<h1>HEJ. Detta är vår webshops index sida</h1>

{% endblock %}